"""empty message

Revision ID: 866c2b203a21
Revises: c354cd1bd629
Create Date: 2020-10-20 09:58:04.651029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866c2b203a21'
down_revision = 'c354cd1bd629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True)) # accept existing records w/o completed

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;') # set their completed column to False

    op.alter_column('todos', sa.Column('completed', sa.Boolean(), nullable=False)) # make completed mandatory again
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
