"""empty message

Revision ID: 8cb5ef78966a
Revises: acaa8f6f84b7
Create Date: 2020-10-26 10:49:12.310289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb5ef78966a'
down_revision = 'acaa8f6f84b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_todolist_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    op.drop_column('todos', 'todolist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('todolist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_todolist_id_fkey', 'todos', 'todolists', ['todolist_id'], ['id'])
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
