"""empty message

Revision ID: 8d57787a18ed
Revises: 0792f340f902
Create Date: 2020-10-26 11:21:31.940431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d57787a18ed'
down_revision = '0792f340f902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'completed')
    # ### end Alembic commands ###
